### ISSUE TITLE
get_pk_constraint should return a dict

### ISSUE THREAD

**Issue by YaPeL** [mxmzdlv/pybigquery#36]
Hi, I'm trying to use pybigquery with sqlalchemy-diff, and one of the issues I found is that sqlalchemy-diff expects a dict for get_pk_constraint containing said constrains, I know BQ doesn't have that, but I assume almost every other dialect has them, so, would it be possible to have something like:
```
    def get_pk_constraint(self, connection, table_name, schema=None, **kw):
        # BigQuery has no support for primary keys.
        return {"constrained_columns": ""}
```
thanks

**Comment by tswast** [comment]
This makes sense to me as a valid feature request, since other plugins such as [sqlalchemy-diff](https://sqlalchemy-diff.readthedocs.io/en/latest/) require it. Agreed that it's always going to return nothing for BigQuery.

Relevant docs: https://docs.sqlalchemy.org/en/13/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_pk_constraint
